### ISSUE TITLE
Training Data Download issue

### ISSUE THREAD

**Issue by yihangyuan** [kouroshHakha/circuit-fewshot-code#1]
Dear author,

I'm trying to download the Rladder and OpAmp pretraining data. Then I meet some problem here.  

# Rladder Data
In README, it said "You can download the tarball [here](https://github.com/kouroshHakha/circuit-fewshot-code/blob/master/anonymized_link) and extract them in rdiv folder (size ~300MB)", which is a 404 page

# OpAmp pretraining data
After environment configuration, I run the code in Jupyter notebook:

`from cgl.data.graph_data import CircuitInMemDataset
from torch_geometric.data import DataLoader

dset = CircuitInMemDataset(root='/tmp/dataset/opamp_pt', mode='train')

sample_data = dset[0]
splits = dset.splits
train_dset = dset[splits['train']]
valid_dset = dset[splits['valid']]
test_dset = dset[splits['test']]

train_dloader = DataLoader(train_dset, batch_size=16)`

**Then it gives the error: BadGzipFile: Not a gzipped file (b'<!')**

**Comment by yihangyuan** [comment]
I figure out the problem for OpAmp dataset. When it try to download the file, google drive return a notification webpage, and said file is too large to scan virus. Then this web page will be downloaded, not the real file. So that's why python show the error:Not a gzipped file (b'<!').

**Comment by MohsenMokrian** [comment]
> I figure out the problem for OpAmp dataset. When it try to download the file, google drive return a notification webpage, and said file is too large to scan virus. Then this web page will be downloaded, not the real file. So that's why python show the error:Not a gzipped file (b'<!').

Dear,

I have the same issue. How did you solve it?

**Comment by MohsenMokrian** [comment]
Also, the tarball Rladder Data link is not working.

**Comment by yihangyuan** [comment]
> > I figure out the problem for OpAmp dataset. When it try to download the file, google drive return a notification webpage, and said file is too large to scan virus. Then this web page will be downloaded, not the real file. So that's why python show the error:Not a gzipped file (b'<!').
> 
> Dear,
> 
> I have the same issue. How did you solve it?

You can check his code, there are google drive file ID for datasets in  graph-data.py.
Rladder datasets address was corrupted. It won't available, unless author fix it.

**Comment by kouroshHakha** [comment]
Hey @MohsenMokrian and @yihangyuan. I have the updated links to the file. Do you guys have a suggestion on how to share the dataset for free more permanently that would not need maintenance?

**Comment by kouroshHakha** [comment]
I added the links to the readme. The rladder one was anonymized before the submission. But for the other two datasets the IDs match with what I have, so I am not sure where the error is coming from.

**Comment by MohsenMokrian** [comment]
> Hey @MohsenMokrian and @yihangyuan. I have the updated links to the file. Do you guys have a suggestion on how to share the dataset for free more permanently that would not need maintenance?

Thanks a lot for adding the links.

**Comment by yihangyuan** [comment]
> I added the links to the readme. The rladder one was anonymized before the submission. But for the other two datasets the IDs match with what I have, so I am not sure where the error is coming from.

Thanks!
